version: '3'

services:
  postgresql:
    container_name: postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: smart_cuisine
      POSTGRES_PASSWORD: forzaMagggicaRoma1
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgresql/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - "5432:5432"
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "smart_cuisine", "-d", "notification_db", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" 
    volumes:
      - ./rabbitmq/rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - rabbit-network

    


  authentication-management:
    container_name: authentication-management
    image: authentication-management
    build:
        context: ./authenticationManagement
    ports:
      - "3000:3000"
    networks:
      - app-network



  userprofile-management:
    container_name: userprofile-management
    image: userprofile-management
    build:
          context: ./userProfileManagement
    ports:
      - "3001:3000"
    networks:
      - rabbit-network
      - app-network
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  shoppinglist-management:
    container_name: shoppinglist-management
    image: shoppinglist-management
    build:
      context: ./shoppingListManagement
    ports:
      - "3002:3000"
    networks:
      - app-network
    depends_on:
      postgresql:
        condition: service_healthy

  notification-management:
    container_name: notification-management
    image: notification-management
    build:
      context: ./notificationManagement
    ports:
      - "3003:3000"
    networks:
      - rabbit-network
      - app-network
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  recipesingredients-management:
    container_name: recipesingredients-management
    image: recipesingredients-management
    build:
      context: ./recipesAndIngredientManagement
    ports:
      - "3004:3000"
    networks:
      - app-network
    depends_on:
      postgresql:
        condition: service_healthy

  storage-management:
    container_name: storage-management
    image: storage-management
    build:
      context: ./storageManagement
    ports:
      - "3005:3000"
    networks:
      - app-network
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  rabbitmq_data:
    driver: local
  
networks:
  rabbit-network:
    driver: bridge

  app-network:
    driver: bridge


